name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 8.x
      - name: Run tests
        run: dotnet test --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.cobertura.xml
          directory: ./tests/Translator.UnitTests
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage reports to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: ./tests/Translator.UnitTests/coverage.cobertura.xml
          base-path: src/Translator
          fail-on-error: true
          measure: true
